import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { DropdownMenuDemo } from "./dropdownMenu";
export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <header className="flex h-14 shrink-0 items-center gap-2">
      <div className="px-3">
        <DropdownMenuDemo />
      </div>
      <div className="ml-auto px-3">
        <DropdownMenuDemo />
      </div>
    </header>
    <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
      {children}
    </div>
    </>
  )
}