import type { Metadata } from "next";

import "@/style/tailwind.css";
import { ThemeProvider } from "@/components/provider/themeProvider"
import { SessionProviders } from "@/components/provider/sessionProvider"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
            <SessionProviders>
              {children}
              </SessionProviders>
          </ThemeProvider>
        </body>
      </html>
      
  );
}
